// Stable hand-maintained API facade. Generated code lives under ./generated/.
export {
  getJobStatusPlanJobIdGet,
  healthHealthGet,
  loginAuthLoginPost,
  logoutAuthLogoutPost,
  meAuthMeGet,
  type Options,
  planPlanPost,
  recomputePlanPlanRecomputePost,
  refreshProsePlanPlanRefreshProsePost,
  registerAuthRegisterPost,
  searchPlacesPlacesSearchPost,
} from "./generated/sdk.gen";
export type {
  AddItem,
  AppliedOffer,
  AwardChartEntry,
  BudgetTotals,
  Channel,
  ClientOptions,
  CostedTrip,
  CredentialsIn,
  DraftItineraryInput,
  DraftItineraryOutput,
  FinalReport,
  GetJobStatusPlanJobIdGetData,
  GetJobStatusPlanJobIdGetError,
  GetJobStatusPlanJobIdGetErrors,
  GetJobStatusPlanJobIdGetResponse,
  GetJobStatusPlanJobIdGetResponses,
  HealthHealthGetData,
  HealthHealthGetResponse,
  HealthHealthGetResponses,
  HttpValidationError,
  InfeasiblePlan,
  ItineraryDayInput,
  ItineraryDayOutput,
  ItineraryItemInput,
  ItineraryItemOutput,
  JobError,
  KernelResult,
  LineAssignment,
  MoveItem,
  OptimizationPrefs,
  OptimizerResult,
  PaymentStrategyRow,
  PipelineStatus,
  PlaceProviderDiagnostic,
  PlaceSearchRequest,
  PlaceSearchResponse,
  PlaceSearchResult,
  PlanJobStatus,
  PlanPlanPostData,
  PlanPlanPostError,
  PlanPlanPostErrors,
  PlanPlanPostResponse,
  PlanPlanPostResponses,
  PoiEvidence,
  Provenance,
  Recommendation,
  RecommendationKind,
  RecomputePlanPlanRecomputePostData,
  RecomputePlanPlanRecomputePostError,
  RecomputePlanPlanRecomputePostErrors,
  RecomputePlanPlanRecomputePostResponse,
  RecomputePlanPlanRecomputePostResponses,
  RecomputeRequest,
  RedemptionPath,
  RefreshProsePlanPlanRefreshProsePostData,
  RefreshProsePlanPlanRefreshProsePostError,
  RefreshProsePlanPlanRefreshProsePostErrors,
  RefreshProsePlanPlanRefreshProsePostResponse,
  RefreshProsePlanPlanRefreshProsePostResponses,
  RefreshProseRequest,
  RegionCapability,
  Rejection,
  RemoveItem,
  ReorderDay,
  ReplaceItem,
  RunnerUp,
  SampleFlight,
  SampleHotel,
  SearchPlacesPlacesSearchPostData,
  SearchPlacesPlacesSearchPostError,
  SearchPlacesPlacesSearchPostErrors,
  SearchPlacesPlacesSearchPostResponse,
  SearchPlacesPlacesSearchPostResponses,
  SectionFreshness,
  SectionState,
  SelectedHotelArea,
  SpendCategory,
  SpendLineItem,
  TransferAdvice,
  TransferPlan,
  TransferStep,
  TransitSegment,
  TripIntakeRequest,
  TripSpec,
  UserOut,
  UserWallet,
  ValidationError,
} from "./generated/types.gen";
import type {
  DraftItineraryOutput,
  ItineraryDayOutput,
  ItineraryItemOutput,
} from "./generated/types.gen";
export { apiClient } from './client-config';
export { parsePlanJobStatus, planJobStatusSchema, sectionFreshnessSchema } from './schemas';
export type DraftItinerary = DraftItineraryOutput;
export type ItineraryDay = ItineraryDayOutput;
export type ItineraryItem = ItineraryItemOutput;
